### ISSUE TITLE
Issue with paddle movement, something wrong with conditions recently added.

### ISSUE THREAD

**Issue by haseebehsan** [haseebehsan/PingPong#2]
Hassan test run the game
-when ball is in upper half, neechy wala paddle is still controllable
-one bug found when ball is in upper half neechy wala paddle can get out of window
![screenshot_20170422-121834 1](https://cloud.githubusercontent.com/assets/10743165/25302366/03708744-2756-11e7-899e-6d313425fcd4.png)

**Comment by MrHassanMurtaza** [comment]
It's​ not.happening on my.mobile. iDK what's the issue. Let me see the
recently added conditions.

**Comment by haseebehsan** [comment]
look it up werna me daikhta isko

**Comment by MrHassanMurtaza** [comment]
Solved now.

**Comment by haseebehsan** [comment]
me check karta...

**Comment by haseebehsan** [comment]
still problem hai... pata kkab hoti hai... when ball is coming down but is still in upper half... paddle is usable and gets out of windows...

**Comment by haseebehsan** [comment]
yeah problem solved.
